import {
  PlusOutlined,
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
  UndoOutlined,
  CloudDownloadOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignBottomOutlined,
  FileTextOutlined,
  StopOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CloseOutlined,
  CloudUploadOutlined,
  RedoOutlined,
} from "@ant-design/icons";
import { CommonObj } from "@/vite-env";

export const btnsMap: CommonObj = {
  add: {
    name: "add",
    text: "新增",
    order: 0,
    auth: [],
    attrs: {
      type: "primary",
      icon: <PlusOutlined />,
      ghost: false,
    },
  },
  delete: {
    name: "delete",
    text: "删除",
    order: 1,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <DeleteOutlined />,
      danger: true,
    },
    popconfirm: true,
  },
  edit: {
    name: "edit",
    text: "编辑",
    order: 2,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <EditOutlined />,
      ghost: true,
    },
  },
  view: {
    name: "view",
    text: "查看",
    order: 3,
    auth: [],
    attrs: {
      type: "primary",
      icon: <EyeOutlined />,
      ghost: true,
    },
  },
  upload: {
    name: "upload",
    text: "上传",
    order: 4,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <CloudUploadOutlined />,
    },
  },
  download: {
    name: "download",
    text: "下载",
    order: 5,
    auth: [],
    attrs: {
      type: "primary",
      icon: <CloudDownloadOutlined />,
      ghost: true,
    },
  },
  import: {
    name: "import",
    text: "导入",
    order: 10,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <VerticalAlignTopOutlined />,
    },
  },
  export: {
    name: "export",
    text: "导出",
    order: 11,
    auth: [],
    attrs: {
      type: "primary",
      icon: <VerticalAlignBottomOutlined />,
      ghost: true,
    },
  },
  enable: {
    name: "enable",
    text: "启用",
    order: 12,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <CheckCircleOutlined />,
    },
    popconfirm: true,
  },
  forbid: {
    name: "forbid",
    text: "禁用",
    order: 13,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <StopOutlined />,
      ghost: true,
    },
    popconfirm: true,
  },
  repeal: {
    name: "repeal",
    text: "撤销",
    order: 20,
    auth: [0, 1, 2],
    attrs: {
      type: "primary",
      icon: <UndoOutlined />,
      ghost: true,
      danger: true,
    },
  },
  log: {
    name: "log",
    text: "日志",
    order: 21,
    auth: [],
    attrs: {
      type: "primary",
      icon: <FileTextOutlined />,
      ghost: true,
    },
  },
  submit: {
    name: "submit",
    text: "提交",
    order: 30,
    auth: [],
    attrs: {
      type: "primary",
      icon: <CloudUploadOutlined />,
      // ghost: true,
    },
  },
  reset: {
    name: "reset",
    text: "重置",
    order: 31,
    auth: [],
    attrs: {
      type: "primary",
      icon: <RedoOutlined />,
      ghost: true,
    },
  },
  pass: {
    name: "pass",
    text: "通过",
    order: 31,
    auth: [],
    attrs: {
      type: "primary",
      icon: <CheckOutlined />,
    },
  },
  reject: {
    name: "reject",
    text: "驳回",
    order: 31,
    auth: [],
    attrs: {
      type: "primary",
      icon: <CloseOutlined />,
      danger: true,
      ghost: true,
    },
  },
  empty: {
    name: "empty",
    text: "empty",
    auth: [],
    attrs: {
      danger: true,
    },
  },
};
